// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2016-04-08 17:16:44 UTC
//   on: 2016-04-28, 20:31:57 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Drive API (drive/v3)
// Generated from:
//   Version: v3
//   Revision: 22
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_DRIVE_API_CHANGE_H_
#define  GOOGLE_DRIVE_API_CHANGE_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/client/util/date_time.h"
#include "googleapis/strings/stringpiece.h"

#include "google/drive_api/file.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_drive_api {
using namespace googleapis;

/**
 * A change to a file.
 *
 * @ingroup DataObject
 */
class Change : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Change* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Change(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Change(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Change();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_drive_api::Change</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_drive_api::Change");
  }

  /**
   * Determine if the '<code>file</code>' attribute was set.
   *
   * @return true if the '<code>file</code>' attribute was set.
   */
  bool has_file() const {
    return Storage().isMember("file");
  }

  /**
   * Clears the '<code>file</code>' attribute.
   */
  void clear_file() {
    MutableStorage()->removeMember("file");
  }


  /**
   * Get a reference to the value of the '<code>file</code>' attribute.
   */
  const File get_file() const;

  /**
   * Gets a reference to a mutable value of the '<code>file</code>' property.
   *
   * The updated state of the file. Present if the file has not been removed.
   *
   * @return The result can be modified to change the attribute value.
   */
  File mutable_file();

  /**
   * Determine if the '<code>fileId</code>' attribute was set.
   *
   * @return true if the '<code>fileId</code>' attribute was set.
   */
  bool has_file_id() const {
    return Storage().isMember("fileId");
  }

  /**
   * Clears the '<code>fileId</code>' attribute.
   */
  void clear_file_id() {
    MutableStorage()->removeMember("fileId");
  }


  /**
   * Get the value of the '<code>fileId</code>' attribute.
   */
  const StringPiece get_file_id() const {
    const Json::Value& v = Storage("fileId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>fileId</code>' attribute.
   *
   * The ID of the file which has changed.
   *
   * @param[in] value The new value.
   */
  void set_file_id(const StringPiece& value) {
    *MutableStorage("fileId") = value.data();
  }

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const StringPiece get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * This is always drive#change.
   *
   * @param[in] value The new value.
   */
  void set_kind(const StringPiece& value) {
    *MutableStorage("kind") = value.data();
  }

  /**
   * Determine if the '<code>removed</code>' attribute was set.
   *
   * @return true if the '<code>removed</code>' attribute was set.
   */
  bool has_removed() const {
    return Storage().isMember("removed");
  }

  /**
   * Clears the '<code>removed</code>' attribute.
   */
  void clear_removed() {
    MutableStorage()->removeMember("removed");
  }


  /**
   * Get the value of the '<code>removed</code>' attribute.
   */
  bool get_removed() const {
    const Json::Value& storage = Storage("removed");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>removed</code>' attribute.
   *
   * Whether the file has been removed from the view of the changes list, for
   * example by deletion or lost access.
   *
   * @param[in] value The new value.
   */
  void set_removed(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("removed"));
  }

  /**
   * Determine if the '<code>time</code>' attribute was set.
   *
   * @return true if the '<code>time</code>' attribute was set.
   */
  bool has_time() const {
    return Storage().isMember("time");
  }

  /**
   * Clears the '<code>time</code>' attribute.
   */
  void clear_time() {
    MutableStorage()->removeMember("time");
  }


  /**
   * Get the value of the '<code>time</code>' attribute.
   */
  client::DateTime get_time() const {
    const Json::Value& storage = Storage("time");
    return client::JsonValueToCppValueHelper<client::DateTime >(storage);
  }

  /**
   * Change the '<code>time</code>' attribute.
   *
   * The time of this change (RFC 3339 date-time).
   *
   * @param[in] value The new value.
   */
  void set_time(client::DateTime value) {
    client::SetJsonValueFromCppValueHelper<client::DateTime >(
      value, MutableStorage("time"));
  }

 private:
  void operator=(const Change&);
};  // Change
}  // namespace google_drive_api
#endif  // GOOGLE_DRIVE_API_CHANGE_H_
